define({
    "name": "flare",
    "children": [{
        "name": "analytics",
        "children": [{
            "name": "cluster",
            "children": [{
                "name": "AgglomerativeCluster",
                "size": 3938,
                "x": 1,
                "none": 1
            }, {
                "name": "CommunityStructure",
                "size": 3812,
                "x": 2,
                "none": 1
            }, {
                "name": "HierarchicalCluster",
                "size": 6714,
                "x": 3,
                "none": 1
            }, {
                "name": "MergeEdge",
                "size": 743,
                "x": 4,
                "none": 1
            }]
        }, {
            "name": "graph",
            "children": [{
                "name": "BetweennessCentrality",
                "size": 3534,
                "x": 1,
                "none": 1
            }, {
                "name": "LinkDistance",
                "size": 5731,
                "x": 2,
                "none": 1
            }, {
                "name": "MaxFlowMinCut",
                "size": 7840,
                "x": 3,
                "none": 1
            }, {
                "name": "ShortestPaths",
                "size": 5914,
                "x": 4,
                "none": 1
            }, {
                "name": "SpanningTree",
                "size": 3416,
                "x": 5,
                "none": 1
            }]
        }, {
            "name": "optimization",
            "children": [{
                "name": "AspectRatioBanker",
                "size": 7074,
                "x": 1,
                "none": 1
            }]
        }]
    }, {
        "name": "animate",
        "children": [{
            "name": "Easing",
            "size": 17010,
            "x": 1,
            "none": 1
        }, {
            "name": "FunctionSequence",
            "size": 5842,
            "x": 2,
            "none": 1
        }, {
            "name": "interpolate",
            "children": [{
                "name": "ArrayInterpolator",
                "size": 1983,
                "x": 1,
                "none": 1
            }, {
                "name": "ColorInterpolator",
                "size": 2047,
                "x": 2,
                "none": 1
            }, {
                "name": "DateInterpolator",
                "size": 1375,
                "x": 3,
                "none": 1
            }, {
                "name": "Interpolator",
                "size": 8746,
                "x": 4,
                "none": 1
            }, {
                "name": "MatrixInterpolator",
                "size": 2202,
                "x": 5,
                "none": 1
            }, {
                "name": "NumberInterpolator",
                "size": 1382,
                "x": 6,
                "none": 1
            }, {
                "name": "ObjectInterpolator",
                "size": 1629,
                "x": 7,
                "none": 1
            }, {
                "name": "PointInterpolator",
                "size": 1675,
                "x": 8,
                "none": 1
            }, {
                "name": "RectangleInterpolator",
                "size": 2042,
                "x": 9,
                "none": 1
            }]
        }, {
            "name": "ISchedulable",
            "size": 1041,
            "x": 3,
            "none": 1
        }, {
            "name": "Parallel",
            "size": 5176,
            "x": 4,
            "none": 1
        }, {
            "name": "Pause",
            "size": 449,
            "x": 5,
            "none": 1
        }, {
            "name": "Scheduler",
            "size": 5593,
            "x": 6,
            "none": 1
        }, {
            "name": "Sequence",
            "size": 5534,
            "x": 7,
            "none": 1
        }, {
            "name": "Transition",
            "size": 9201,
            "x": 8,
            "none": 1
        }, {
            "name": "Transitioner",
            "size": 19975,
            "x": 9,
            "none": 1
        }, {
            "name": "TransitionEvent",
            "size": 1116,
            "x": 10,
            "none": 1
        }, {
            "name": "Tween",
            "size": 6006,
            "x": 11,
            "none": 1
        }]
    }, {
        "name": "datas",
        "children": [{
            "name": "converters",
            "children": [{
                "name": "Converters",
                "size": 721,
                "x": 1,
                "none": 1
            }, {
                "name": "DelimitedTextConverter",
                "size": 4294,
                "x": 2,
                "none": 1
            }, {
                "name": "GraphMLConverter",
                "size": 9800,
                "x": 3,
                "none": 1
            }, {
                "name": "IDataConverter",
                "size": 1314,
                "x": 4,
                "none": 1
            }, {
                "name": "JSONConverter",
                "size": 2220,
                "x": 5,
                "none": 1
            }]
        }, {
            "name": "DataField",
            "size": 1759,
            "x": 1,
            "none": 1
        }, {
            "name": "DataSchema",
            "size": 2165,
            "x": 2,
            "none": 1
        }, {
            "name": "DataSet",
            "size": 586,
            "x": 3,
            "none": 1
        }, {
            "name": "DataSource",
            "size": 3331,
            "x": 4,
            "none": 1
        }, {
            "name": "DataTable",
            "size": 772,
            "x": 5,
            "none": 1
        }, {
            "name": "DataUtil",
            "size": 3322,
            "x": 6,
            "none": 1
        }]
    }, {
        "name": "display",
        "children": [{
            "name": "DirtySprite",
            "size": 8833,
            "x": 1,
            "none": 1
        }, {
            "name": "LineSprite",
            "size": 1732,
            "x": 2,
            "none": 1
        }, {
            "name": "RectSprite",
            "size": 3623,
            "x": 3,
            "none": 1
        }, {
            "name": "TextSprite",
            "size": 10066,
            "x": 4,
            "none": 1
        }]
    }, {
        "name": "flex",
        "children": [{
            "name": "FlareVis",
            "size": 4116,
            "x": 1,
            "none": 1
        }]
    }, {
        "name": "physics",
        "children": [{
            "name": "DragForce",
            "size": 1082,
            "x": 1,
            "none": 1
        }, {
            "name": "GravityForce",
            "size": 1336,
            "x": 2,
            "none": 1
        }, {
            "name": "IForce",
            "size": 319,
            "x": 3,
            "none": 1
        }, {
            "name": "NBodyForce",
            "size": 10498,
            "x": 4,
            "none": 1
        }, {
            "name": "Particle",
            "size": 2822,
            "x": 5,
            "none": 1
        }, {
            "name": "Simulation",
            "size": 9983,
            "x": 6,
            "none": 1
        }, {
            "name": "Spring",
            "size": 2213,
            "x": 7,
            "none": 1
        }, {
            "name": "SpringForce",
            "size": 1681,
            "x": 8,
            "none": 1
        }]
    }, {
        "name": "query",
        "children": [{
            "name": "AggregateExpression",
            "size": 1616,
            "x": 1,
            "none": 1
        }, {
            "name": "And",
            "size": 1027,
            "x": 2,
            "none": 1
        }, {
            "name": "Arithmetic",
            "size": 3891,
            "x": 3,
            "none": 1
        }, {
            "name": "Average",
            "size": 891,
            "x": 4,
            "none": 1
        }, {
            "name": "BinaryExpression",
            "size": 2893,
            "x": 5,
            "none": 1
        }, {
            "name": "Comparison",
            "size": 5103,
            "x": 6,
            "none": 1
        }, {
            "name": "CompositeExpression",
            "size": 3677,
            "x": 7,
            "none": 1
        }, {
            "name": "Count",
            "size": 781,
            "x": 8,
            "none": 1
        }, {
            "name": "DateUtil",
            "size": 4141,
            "x": 9,
            "none": 1
        }, {
            "name": "Distinct",
            "size": 933,
            "x": 10,
            "none": 1
        }, {
            "name": "Expression",
            "size": 5130,
            "x": 11,
            "none": 1
        }, {
            "name": "ExpressionIterator",
            "size": 3617,
            "x": 12,
            "none": 1
        }, {
            "name": "Fn",
            "size": 3240,
            "x": 13,
            "none": 1
        }, {
            "name": "If",
            "size": 2732,
            "x": 14,
            "none": 1
        }, {
            "name": "IsA",
            "size": 2039,
            "x": 15,
            "none": 1
        }, {
            "name": "Literal",
            "size": 1214,
            "x": 16,
            "none": 1
        }, {
            "name": "Match",
            "size": 3748,
            "x": 17,
            "none": 1
        }, {
            "name": "Maximum",
            "size": 843,
            "x": 18,
            "none": 1
        }, {
            "name": "methods",
            "children": [{
                "name": "add",
                "size": 593,
                "x": 1,
                "none": 1
            }, {
                "name": "and",
                "size": 330,
                "x": 2,
                "none": 1
            }, {
                "name": "average",
                "size": 287,
                "x": 3,
                "none": 1
            }, {
                "name": "count",
                "size": 277,
                "x": 4,
                "none": 1
            }, {
                "name": "distinct",
                "size": 292,
                "x": 5,
                "none": 1
            }, {
                "name": "div",
                "size": 595,
                "x": 6,
                "none": 1
            }, {
                "name": "eq",
                "size": 594,
                "x": 7,
                "none": 1
            }, {
                "name": "fn",
                "size": 460,
                "x": 8,
                "none": 1
            }, {
                "name": "gt",
                "size": 603,
                "x": 9,
                "none": 1
            }, {
                "name": "gte",
                "size": 625,
                "x": 10,
                "none": 1
            }, {
                "name": "iff",
                "size": 748,
                "x": 11,
                "none": 1
            }, {
                "name": "isa",
                "size": 461,
                "x": 12,
                "none": 1
            }, {
                "name": "lt",
                "size": 597,
                "x": 13,
                "none": 1
            }, {
                "name": "lte",
                "size": 619,
                "x": 14,
                "none": 1
            }, {
                "name": "max",
                "size": 283,
                "x": 15,
                "none": 1
            }, {
                "name": "min",
                "size": 283,
                "x": 16,
                "none": 1
            }, {
                "name": "mod",
                "size": 591,
                "x": 17,
                "none": 1
            }, {
                "name": "mul",
                "size": 603,
                "x": 18,
                "none": 1
            }, {
                "name": "neq",
                "size": 599,
                "x": 19,
                "none": 1
            }, {
                "name": "not",
                "size": 386,
                "x": 20,
                "none": 1
            }, {
                "name": "or",
                "size": 323,
                "x": 21,
                "none": 1
            }, {
                "name": "orderby",
                "size": 307,
                "x": 22,
                "none": 1
            }, {
                "name": "range",
                "size": 772,
                "x": 23,
                "none": 1
            }, {
                "name": "select",
                "size": 296,
                "x": 24,
                "none": 1
            }, {
                "name": "stddev",
                "size": 363,
                "x": 25,
                "none": 1
            }, {
                "name": "sub",
                "size": 600,
                "x": 26,
                "none": 1
            }, {
                "name": "sum",
                "size": 280,
                "x": 27,
                "none": 1
            }, {
                "name": "update",
                "size": 307,
                "x": 28,
                "none": 1
            }, {
                "name": "variance",
                "size": 335,
                "x": 29,
                "none": 1
            }, {
                "name": "where",
                "size": 299,
                "x": 30,
                "none": 1
            }, {
                "name": "xor",
                "size": 354,
                "x": 31,
                "none": 1
            }, {
                "name": "_",
                "size": 264,
                "x": 32,
                "none": 1
            }]
        }, {
            "name": "Minimum",
            "size": 843,
            "x": 19,
            "none": 1
        }, {
            "name": "Not",
            "size": 1554,
            "x": 20,
            "none": 1
        }, {
            "name": "Or",
            "size": 970,
            "x": 21,
            "none": 1
        }, {
            "name": "Query",
            "size": 13896,
            "x": 22,
            "none": 1
        }, {
            "name": "Range",
            "size": 1594,
            "x": 23,
            "none": 1
        }, {
            "name": "StringUtil",
            "size": 4130,
            "x": 24,
            "none": 1
        }, {
            "name": "Sum",
            "size": 791,
            "x": 25,
            "none": 1
        }, {
            "name": "Variable",
            "size": 1124,
            "x": 26,
            "none": 1
        }, {
            "name": "Variance",
            "size": 1876,
            "x": 27,
            "none": 1
        }, {
            "name": "Xor",
            "size": 1101,
            "x": 28,
            "none": 1
        }]
    }, {
        "name": "scale",
        "children": [{
            "name": "IScaleMap",
            "size": 2105,
            "x": 1,
            "none": 1
        }, {
            "name": "LinearScale",
            "size": 1316,
            "x": 2,
            "none": 1
        }, {
            "name": "LogScale",
            "size": 3151,
            "x": 3,
            "none": 1
        }, {
            "name": "OrdinalScale",
            "size": 3770,
            "x": 4,
            "none": 1
        }, {
            "name": "QuantileScale",
            "size": 2435,
            "x": 5,
            "none": 1
        }, {
            "name": "QuantitativeScale",
            "size": 4839,
            "x": 6,
            "none": 1
        }, {
            "name": "RootScale",
            "size": 1756,
            "x": 7,
            "none": 1
        }, {
            "name": "Scale",
            "size": 4268,
            "x": 8,
            "none": 1
        }, {
            "name": "ScaleType",
            "size": 1821,
            "x": 9,
            "none": 1
        }, {
            "name": "TimeScale",
            "size": 5833,
            "x": 10,
            "none": 1
        }]
    }, {
        "name": "util",
        "children": [{
            "name": "Arrays",
            "size": 8258,
            "x": 1,
            "none": 1
        }, {
            "name": "Colors",
            "size": 10001,
            "x": 2,
            "none": 1
        }, {
            "name": "Dates",
            "size": 8217,
            "x": 3,
            "none": 1
        }, {
            "name": "Displays",
            "size": 12555,
            "x": 4,
            "none": 1
        }, {
            "name": "Filter",
            "size": 2324,
            "x": 5,
            "none": 1
        }, {
            "name": "Geometry",
            "size": 10993,
            "x": 6,
            "none": 1
        }, {
            "name": "heap",
            "children": [{
                "name": "FibonacciHeap",
                "size": 9354,
                "x": 1,
                "none": 1
            }, {
                "name": "HeapNode",
                "size": 1233,
                "x": 2,
                "none": 1
            }]
        }, {
            "name": "IEvaluable",
            "size": 335,
            "x": 7,
            "none": 1
        }, {
            "name": "IPredicate",
            "size": 383,
            "x": 8,
            "none": 1
        }, {
            "name": "IValueProxy",
            "size": 874,
            "x": 9,
            "none": 1
        }, {
            "name": "math",
            "children": [{
                "name": "DenseMatrix",
                "size": 3165,
                "x": 1,
                "none": 1
            }, {
                "name": "IMatrix",
                "size": 2815,
                "x": 2,
                "none": 1
            }, {
                "name": "SparseMatrix",
                "size": 3366,
                "x": 3,
                "none": 1
            }]
        }, {
            "name": "Maths",
            "size": 17705,
            "x": 10,
            "none": 1
        }, {
            "name": "Orientation",
            "size": 1486,
            "x": 11,
            "none": 1
        }, {
            "name": "palette",
            "children": [{
                "name": "ColorPalette",
                "size": 6367,
                "x": 1,
                "none": 1
            }, {
                "name": "Palette",
                "size": 1229,
                "x": 2,
                "none": 1
            }, {
                "name": "ShapePalette",
                "size": 2059,
                "x": 3,
                "none": 1
            }, {
                "name": "SizePalette",
                "size": 2291,
                "x": 4,
                "none": 1
            }]
        }, {
            "name": "Property",
            "size": 5559,
            "x": 12,
            "none": 1
        }, {
            "name": "Shapes",
            "size": 19118,
            "x": 13,
            "none": 1
        }, {
            "name": "Sort",
            "size": 6887,
            "x": 14,
            "none": 1
        }, {
            "name": "Stats",
            "size": 6557,
            "x": 15,
            "none": 1
        }, {
            "name": "Strings",
            "size": 22026,
            "x": 16,
            "none": 1
        }]
    }, {
        "name": "vis",
        "children": [{
            "name": "axis",
            "children": [{
                "name": "Axes",
                "size": 1302,
                "x": 1,
                "none": 1
            }, {
                "name": "Axis",
                "size": 24593,
                "x": 2,
                "none": 1
            }, {
                "name": "AxisGridLine",
                "size": 652,
                "x": 3,
                "none": 1
            }, {
                "name": "AxisLabel",
                "size": 636,
                "x": 4,
                "none": 1
            }, {
                "name": "CartesianAxes",
                "size": 6703,
                "x": 5,
                "none": 1
            }]
        }, {
            "name": "controls",
            "children": [{
                "name": "AnchorControl",
                "size": 2138,
                "x": 1,
                "none": 1
            }, {
                "name": "ClickControl",
                "size": 3824,
                "x": 2,
                "none": 1
            }, {
                "name": "Control",
                "size": 1353,
                "x": 3,
                "none": 1
            }, {
                "name": "ControlList",
                "size": 4665,
                "x": 4,
                "none": 1
            }, {
                "name": "DragControl",
                "size": 2649,
                "x": 5,
                "none": 1
            }, {
                "name": "ExpandControl",
                "size": 2832,
                "x": 6,
                "none": 1
            }, {
                "name": "HoverControl",
                "size": 4896,
                "x": 7,
                "none": 1
            }, {
                "name": "IControl",
                "size": 763,
                "x": 8,
                "none": 1
            }, {
                "name": "PanZoomControl",
                "size": 5222,
                "x": 9,
                "none": 1
            }, {
                "name": "SelectionControl",
                "size": 7862,
                "x": 10,
                "none": 1
            }, {
                "name": "TooltipControl",
                "size": 8435,
                "x": 11,
                "none": 1
            }]
        }, {
            "name": "data",
            "children": [{
                "name": "Data",
                "size": 20544,
                "x": 1,
                "none": 1
            }, {
                "name": "DataList",
                "size": 19788,
                "x": 2,
                "none": 1
            }, {
                "name": "DataSprite",
                "size": 10349,
                "x": 3,
                "none": 1
            }, {
                "name": "EdgeSprite",
                "size": 3301,
                "x": 4,
                "none": 1
            }, {
                "name": "NodeSprite",
                "size": 19382,
                "x": 5,
                "none": 1
            }, {
                "name": "render",
                "children": [{
                    "name": "ArrowType",
                    "size": 698,
                    "x": 1,
                    "none": 1
                }, {
                    "name": "EdgeRenderer",
                    "size": 5569,
                    "x": 2,
                    "none": 1
                }, {
                    "name": "IRenderer",
                    "size": 353,
                    "x": 3,
                    "none": 1
                }, {
                    "name": "ShapeRenderer",
                    "size": 2247,
                    "x": 4,
                    "none": 1
                }]
            }, {
                "name": "ScaleBinding",
                "size": 11275,
                "x": 6,
                "none": 1
            }, {
                "name": "Tree",
                "size": 7147,
                "x": 7,
                "none": 1
            }, {
                "name": "TreeBuilder",
                "size": 9930,
                "x": 8,
                "none": 1
            }]
        }, {
            "name": "events",
            "children": [{
                "name": "DataEvent",
                "size": 2313,
                "x": 1,
                "none": 1
            }, {
                "name": "SelectionEvent",
                "size": 1880,
                "x": 2,
                "none": 1
            }, {
                "name": "TooltipEvent",
                "size": 1701,
                "x": 3,
                "none": 1
            }, {
                "name": "VisualizationEvent",
                "size": 1117,
                "x": 4,
                "none": 1
            }]
        }, {
            "name": "legend",
            "children": [{
                "name": "Legend",
                "size": 20859,
                "x": 1,
                "none": 1
            }, {
                "name": "LegendItem",
                "size": 4614,
                "x": 2,
                "none": 1
            }, {
                "name": "LegendRange",
                "size": 10530,
                "x": 3,
                "none": 1
            }]
        }, {
            "name": "operator",
            "children": [{
                "name": "distortion",
                "children": [{
                    "name": "BifocalDistortion",
                    "size": 4461,
                    "x": 1,
                    "none": 1
                }, {
                    "name": "Distortion",
                    "size": 6314,
                    "x": 2,
                    "none": 1
                }, {
                    "name": "FisheyeDistortion",
                    "size": 3444,
                    "x": 3,
                    "none": 1
                }]
            }, {
                "name": "encoder",
                "children": [{
                    "name": "ColorEncoder",
                    "size": 3179,
                    "x": 1,
                    "none": 1
                }, {
                    "name": "Encoder",
                    "size": 4060,
                    "x": 2,
                    "none": 1
                }, {
                    "name": "PropertyEncoder",
                    "size": 4138,
                    "x": 3,
                    "none": 1
                }, {
                    "name": "ShapeEncoder",
                    "size": 1690,
                    "x": 4,
                    "none": 1
                }, {
                    "name": "SizeEncoder",
                    "size": 1830,
                    "x": 5,
                    "none": 1
                }]
            }, {
                "name": "filter",
                "children": [{
                    "name": "FisheyeTreeFilter",
                    "size": 5219,
                    "x": 1,
                    "none": 1
                }, {
                    "name": "GraphDistanceFilter",
                    "size": 3165,
                    "x": 2,
                    "none": 1
                }, {
                    "name": "VisibilityFilter",
                    "size": 3509,
                    "x": 3,
                    "none": 1
                }]
            }, {
                "name": "IOperator",
                "size": 1286,
                "x": 1,
                "none": 1
            }, {
                "name": "label",
                "children": [{
                    "name": "Labeler",
                    "size": 9956,
                    "x": 1,
                    "none": 1
                }, {
                    "name": "RadialLabeler",
                    "size": 3899,
                    "x": 2,
                    "none": 1
                }, {
                    "name": "StackedAreaLabeler",
                    "size": 3202,
                    "x": 3,
                    "none": 1
                }]
            }, {
                "name": "layout",
                "children": [{
                    "name": "AxisLayout",
                    "size": 6725,
                    "x": 1,
                    "none": 1
                }, {
                    "name": "BundledEdgeRouter",
                    "size": 3727,
                    "x": 2,
                    "none": 1
                }, {
                    "name": "CircleLayout",
                    "size": 9317,
                    "x": 3,
                    "none": 1
                }, {
                    "name": "CirclePackingLayout",
                    "size": 12003,
                    "x": 4,
                    "none": 1
                }, {
                    "name": "DendrogramLayout",
                    "size": 4853,
                    "x": 5,
                    "none": 1
                }, {
                    "name": "ForceDirectedLayout",
                    "size": 8411,
                    "x": 6,
                    "none": 1
                }, {
                    "name": "IcicleTreeLayout",
                    "size": 4864,
                    "x": 7,
                    "none": 1
                }, {
                    "name": "IndentedTreeLayout",
                    "size": 3174,
                    "x": 8,
                    "none": 1
                }, {
                    "name": "Layout",
                    "size": 7881,
                    "x": 9,
                    "none": 1
                }, {
                    "name": "NodeLinkTreeLayout",
                    "size": 12870,
                    "x": 10,
                    "none": 1
                }, {
                    "name": "PieLayout",
                    "size": 2728,
                    "x": 11,
                    "none": 1
                }, {
                    "name": "RadialTreeLayout",
                    "size": 12348,
                    "x": 12,
                    "none": 1
                }, {
                    "name": "RandomLayout",
                    "size": 870,
                    "x": 13,
                    "none": 1
                }, {
                    "name": "StackedAreaLayout",
                    "size": 9121,
                    "x": 14,
                    "none": 1
                }, {
                    "name": "TreeMapLayout",
                    "size": 9191,
                    "x": 15,
                    "none": 1
                }]
            }, {
                "name": "Operator",
                "size": 2490,
                "x": 2,
                "none": 1
            }, {
                "name": "OperatorList",
                "size": 5248,
                "x": 3,
                "none": 1
            }, {
                "name": "OperatorSequence",
                "size": 4190,
                "x": 4,
                "none": 1
            }, {
                "name": "OperatorSwitch",
                "size": 2581,
                "x": 5,
                "none": 1
            }, {
                "name": "SortOperator",
                "size": 2023,
                "x": 6,
                "none": 1
            }]
        }, {
            "name": "Visualization",
            "size": 16540,
            "x": 1,
            "none": 1
        }]
    }]
});